version: "3.7"
services:
  server:
    build:
      context: server
    ports:
      - 80:5000
    networks:
      - elk

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:$ELK_VERSION
    container_name: elastic
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:$ELK_VERSION
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
    ports:
      - 5601:5601
    depends_on:
      - elastic
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:$ELK_VERSION
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - 5000:5000
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elastic
    networks:
      - elk

networks:
  elk:
    driver: bridge

volumes:
  elastic-data:
    driver: local


